service: aws-services-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    NODE_ENV: production
  timeout: 30
  memorySize: 512

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - access_key
              - secret_key
            allowCredentials: true

# custom:
#   customDomain:
#     domainName: api-${self:provider.stage}.sstechnologies-cloud.com
#     basePath: ''
#     stage: ${self:provider.stage}
#     createRoute53Record: true
#     certificateName: 'sstechnologies-cloud.com'
#     hostedZoneId: Z07937031ROGP6XAEMPWJ

plugins:
  # - serverless-domain-manager
  - serverless-offline

package:
  exclude:
    - .git/**
    - .env
    - README.md
    - test-*.js
    - uploads/**
    - downloads/**